version: '3.1'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: cursojs
      POSTGRES_USER: cursojs
      POSTGRES_PASSWORD: cursojs
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 54327:5432